import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function about() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Ukraine Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.nav}>
                <ul className={styles.ul}>
                    <li className={styles.li}>
                        <Link href="/">
                            <a className={styles.a}>Home</a>
                        </Link>
                    </li>
                    <li className={styles.li}>
                        <Link href="/">
                            <a className={styles.a}>About</a>
                        </Link>
                    </li>
                </ul>
            </nav>
        </div>
    )
}