import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'


export default function about() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Ukraine Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <nav className={styles.nav}>
                <ul className={styles.ul}>
                    <li className={styles.li}>
                        <Link href="/">
                            <a className={styles.a}>Ukraine Blog</a>
                        </Link>
                    </li>
                    <li className={styles.li}>
                        <Link href="/">
                            <a className={styles.a}>Home</a>
                        </Link>
                    </li>
                    <li className={styles.li}>
                        <Link href="/about">
                            <a className={styles.a}>About</a>
                        </Link>
                    </li>
                </ul>
            </nav>
            <div className={styles.about}>
                <Link href="https://github.com/drjoeycadieux/ukraine-blog">
                    <a className={styles.link}>Developed By Joey Cadieux</a>
                </Link>
                <h1 className={styles.text}>
                    Programmer, Security Researcher, Software Developer & Consultant
                </h1>
            </div>
        </div>
    )
}