import Head from 'next/head'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Suspense } from 'react'

const DynamicHeader = dynamic(() => import('../components/header'), {
  suspense: true,
})


import headerPic from '../public/uk.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ukraine Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Suspense fallback={`Loading...`}>
        <DynamicHeader />
      </Suspense>
      <nav className={styles.nav}>
        <ul className={styles.ul}>
          <li className={styles.li}>
            <Link href="/">
              <a className={styles.a}>Ukraine Blog</a>
            </Link>
          </li>
          <li className={styles.li}>
            <Link href="/">
              <a className={styles.a}>Home</a>
            </Link>
          </li>
          <li className={styles.li}>
            <Link href="/about">
              <a className={styles.a}>About</a>
            </Link>
          </li>
        </ul>
      </nav>
      <div className={styles.header}>
        <Image
          src={headerPic}
          alt="Picture of the author"
        />
        <h1 className={styles.h1}>
          Ukraine is a country known for its beautiful and diverse landscape, well-preserved culture and tradition, beautiful women and a terrible nuclear disaster. Actually, Ukraine is the largest country in Europe, not including Russia.
        </h1>
      </div>
      <div className={styles.footer}>
        <p className={styles.footerp}>
          &copy; Copyright Ukraine Blog. Developed By Joey Cadieux
        </p>
      </div>
    </div>
  )
}
